name: Build and Push Docker Image
on:
    workflow_dispatch:

jobs:
    Build-and-Push:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: |
                docker build -t vidsyhq/go-base:latest .
            - name: Push
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                docker push vidsyhq/go-base:latest